import type { EditorFieldDef } from '../components/themes/theme-editor-sidebar/theme-editor-sidebar.types';

/** Shopify-style announcement bar section settings (blueprint paths — remapped per instance in sidebar). */
export const ANNOUNCEMENT_BAR_SETTINGS_FIELDS: EditorFieldDef[] = [
  {
    path: 'sections.announcement_bar.settings.timeToNext',
    type: 'number',
    label: 'Time to next announcement',
    group: 'General',
    widget: 'slider',
    min: 2,
    max: 30,
    step: 1,
    unit: 'sec',
    sidebar: false,
  },
  {
    path: 'sections.announcement_bar.settings.sectionWidth',
    type: 'select',
    label: 'Section width',
    group: 'Appearance',
    widget: 'segmented',
    options: [
      { value: 'page', label: 'Page' },
      { value: 'full', label: 'Full' },
    ],
    sidebar: false,
  },
  {
    path: 'sections.announcement_bar.settings.colorScheme',
    type: 'select',
    label: 'Color scheme',
    group: 'Appearance',
    widget: 'color-scheme',
    options: [
      { value: 'scheme-1', label: 'Scheme 1' },
      { value: 'scheme-2', label: 'Scheme 2' },
      { value: 'scheme-3', label: 'Scheme 3' },
      { value: 'scheme-4', label: 'Scheme 4' },
    ],
    sidebar: false,
  },
  {
    path: 'sections.announcement_bar.settings.dividerThickness',
    type: 'number',
    label: 'Divider thickness',
    group: 'Appearance',
    widget: 'slider',
    min: 0,
    max: 20,
    step: 1,
    unit: 'px',
    sidebar: false,
  },
  {
    path: 'sections.announcement_bar.settings.paddingTop',
    type: 'number',
    label: 'Top',
    group: 'Padding',
    widget: 'slider',
    min: 0,
    max: 80,
    step: 1,
    unit: 'px',
    sidebar: false,
  },
  {
    path: 'sections.announcement_bar.settings.paddingBottom',
    type: 'number',
    label: 'Bottom',
    group: 'Padding',
    widget: 'slider',
    min: 0,
    max: 80,
    step: 1,
    unit: 'px',
    sidebar: false,
  },
  {
    path: 'sections.announcement_bar.settings.customCss',
    type: 'textarea',
    label: 'Custom CSS',
    group: 'Custom CSS',
    widget: 'accordion',
    sidebar: false,
  },
  {
    path: 'sections.announcement_bar.settings.enabled',
    type: 'boolean',
    label: 'Show announcement',
    group: 'General',
    sidebar: false,
  },
];

export const ANNOUNCEMENT_BAR_DEFAULT_SETTINGS: Record<string, unknown> = {
  enabled: true,
  timeToNext: 5,
  sectionWidth: 'page',
  colorScheme: 'scheme-4',
  dividerThickness: 0,
  paddingTop: 15,
  paddingBottom: 15,
  customCss: '',
  message: 'Shop our latest arrivals!',
  linkLabel: '',
  linkHref: '/products',
  dismissible: false,
  icon: '',
};
